// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © elmsource190

//@version=4
study(shorttitle="BB RSI", title="Bollinger Bands RSI", overlay=true, resolution="")
position_mode = ''
position_mode := na(position_mode[1])?na:position_mode[1]

length = input(25, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50, title="StdDev")
basis = sma(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input(0, "Offset", type = input.integer, minval = -500, maxval = 500)
plot(basis, "Basis", color=color.yellow,linewidth=3, offset = offset)
p1 = plot(upper, "Upper", color=#00bcd4,linewidth=3, offset = offset)
p2 = plot(lower, "Lower", color=#00bcd4,linewidth=3, offset = offset)
fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))


len = input(14, minval=1, title="Length")
rsi_src = input(close, "Source", type = input.source)
up = rma(max(change(rsi_src), 0), len)
down = rma(-min(change(rsi_src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))


longSignal = low < lower and rsi < 30
if(longSignal)
    position_mode := 'long'
plotshape(longSignal,location=location.belowbar,style=shape.triangleup,color=color.green)
alertcondition(longSignal,title="BB RSI buy signal",message="BB RSI buy signal")

shortSignal = high > upper and rsi > 70
if(shortSignal)
    position_mode := 'short'
plotshape(shortSignal,location=location.abovebar,style=shape.triangledown,color=color.red)
alertcondition(shortSignal,title="BB RSI buy signal",message="BB RSI buy signal")

exitSignal = (cross(close,basis) or cross(high,basis) or cross(low,basis)) and position_mode != 'exit'
if(exitSignal)
    position_mode := 'exit'
plotshape(exitSignal,location=location.abovebar,style=shape.flag,color=color.yellow,title="exit")
alertcondition(exitSignal,title="BB RSI exit signal",message="BB RSI exit signal")