// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © elmsource190

//@version=4
// study(shorttitle="BB RSI", title="Bollinger Bands RSI", overlay=true, resolution="")
strategy("BB_RSI", overlay=true, initial_capital=100000, 
     commission_type=strategy.commission.percent, 
     commission_value=0.1,currency=currency.USD,pyramiding=5)
position_mode = ''
position_mode := na(position_mode[1])?na:position_mode[1]


// ORDER SIZE SETTINGS
order_size = input(title="Order Size", group="ORDER SIZE SETTINGS", type=input.integer, defval=100)
leverage = input(title="Leverage", group="ORDER SIZE SETTINGS", type=input.integer, defval=1)

// Date 
start_date =  input(title="Start Date", type=input.time,  group="TIME RANGE", defval=timestamp("01 Jul 2021 00:00 +0300"))
end_date =  input(title="End Date", type=input.time, group="TIME RANGE", defval=timestamp("01 Jan 2022 00:00 +0300"))
isDate = time >= start_date and time <= end_date  


length = input(25, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50, title="StdDev")
basis = sma(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input(0, "Offset", type = input.integer, minval = -500, maxval = 500)
// plot(basis, "Basis", color=color.yellow,linewidth=3, offset = offset)
// p1 = plot(upper, "Upper", color=#00bcd4,linewidth=3, offset = offset)
// p2 = plot(lower, "Lower", color=#00bcd4,linewidth=3, offset = offset)
// fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))


len = input(14, minval=1, title="Length")
rsi_src = input(close, "Source", type = input.source)
up = rma(max(change(rsi_src), 0), len)
down = rma(-min(change(rsi_src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))


longSignal = cross(close,lower) and rsi < 30
if(longSignal and isDate)
    position_mode := 'long'
    //
    qty =  strategy.position_size ? strategy.position_size * 2 : order_size/close*leverage
    strategy.entry("enter",strategy.long, qty=qty)
plotshape(longSignal,location=location.belowbar,style=shape.triangleup,color=color.green)

// alertcondition(longSignal,title="BB RSI buy signal",message="BB RSI buy signal")

shortSignal = cross(close,upper) and rsi > 70
if(shortSignal and isDate)
    position_mode := 'short'
    qty = strategy.position_size? strategy.position_size * 2 * -1 : order_size/close*leverage
    strategy.entry("enter",strategy.short, qty=qty)
plotshape(shortSignal,location=location.abovebar,style=shape.triangledown,color=color.red)
// alertcondition(shortSignal,title="BB RSI buy signal",message="BB RSI buy signal")

exitSignal = (cross(close,basis) or cross(high,basis) or cross(low,basis)) and position_mode != 'exit' and isDate
if(exitSignal)
    position_mode := 'exit'
    strategy.exit('exit','enter',limit=close)
plotshape(exitSignal,location=location.abovebar,style=shape.flag,color=color.yellow,title="exit")

// alertcondition(exitSignal,title="BB RSI exit signal",message="BB RSI exit signal")