// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © elmsource133

//@version=4
study("DeMark9", overlay=true,resolution="")
days = input(4, minval=1, title="days before")
TD = 0
TS = 0
TD := close > close[days]? nz(TD[1])+1:0
TS := close < close[days]? nz(TD[1])+1:0
TDUp = TD - valuewhen(TD < TD[1], TD, 1)   
TDDn = TS - valuewhen(TS < TS[1], TS, 1)   

plotshape(TDUp==7, style=shape.triangledown, color=color.white, text="7", textcolor=color.green, location=location.abovebar)
plotshape(TDUp==8, style=shape.triangledown, color=color.white, text="8", textcolor=color.green, location=location.abovebar)
plotshape(TDUp==9, style=shape.triangledown, color=color.white, text="⚠️", textcolor=color.green, location=location.abovebar)
plotshape(TDDn==7, style=shape.triangledown, color=color.white, text="7", textcolor=color.red, location=location.belowbar)
plotshape(TDDn==8, style=shape.triangledown, color=color.white, text="8", textcolor=color.red, location=location.belowbar)
plotshape(TDDn==9, style=shape.triangledown, color=color.white, text="✅", textcolor=color.red, location=location.belowbar)




// plot(close)